language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
os:
  - linux
  - osx
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/keybase/go-updater/test
script:
    # staticcheck only works for two newest go versions
    - if [[ "$(go version)" =~ go1.1[12] ]]; then go get honnef.co/go/tools/cmd/staticcheck && staticcheck ./... && echo "staticcheck complete"; fi
  - go vet ./...
  - go test -v -coverprofile=command.coverprofile ./command
  - go test -v -coverprofile=keybase.coverprofile ./keybase
  - go test -v -coverprofile=process.coverprofile ./process
  - go test -v -coverprofile=saltpack.coverprofile ./saltpack
  - go test -v -coverprofile=service.coverprofile ./service
  - go test -v -coverprofile=sources.coverprofile ./sources
  - go test -v -coverprofile=util.coverprofile ./util
  - go test -v -coverprofile=watchdog.coverprofile ./watchdog
  - go test -v -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
